version: '3'

services:
  namenode:
    image: khalibre/hadoop-namenode:3.3.6
    networks:
      - hbase
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: khalibre/hadoop-datanode:3.3.6
    networks:
      - hbase
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"

  resourcemanager:
    image: khalibre/hadoop-resourcemanager:3.3.6
    networks:
      - hbase
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: khalibre/hadoop-nodemanager:3.3.6
    networks:
      - hbase
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: khalibre/hadoop-historyserver:3.3.6
    networks:
      - hbase
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  hbase:
